on: [push]

name: AzureLoginSample

jobs:
      build-and-deploy:
            runs-on: ubuntu-latest
            steps:

                - name: Log in with Azure
                  uses: azure/login@v1
                  with:
                        creds: ${{ secrets.AZURE_CREDENTIALS }}

                - name: Azure CLI script
                  uses: azure/CLI@v1
                  with:
                    azcliversion: 2.0.72
                    inlineScript: |
                        az account show
                        az storage -h
                        - name: Set up Terraform
                          uses: hashicorp/setup-terraform@v1
                          with:
                          terraform_version: 1.1.0
          
                        - name: Initialize Terraform
                          run: terraform init

                        - name: Validate Terraform Configuration
                          run: terraform validate

                        - name: Create Azure Resources with Terraform
                          run: terraform apply -auto-approve
